#include "maxine_effect_registry.h"
#include "nvafx_types.h"
#include <string.h>

static const struct maxine_effect_info effect_table[] = {
    // --- Single effects ---
    {
        .id               = "denoiser",
        .effect_selector  = NVAFX_EFFECT_DENOISER,
        .display_name     = "Noise Removal",
        .description      = "Removes background noise from speech audio",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = true,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "denoiser",
        .category          = "noise",
    },
    {
        .id               = "dereverb",
        .effect_selector  = NVAFX_EFFECT_DEREVERB,
        .display_name     = "Room Echo Removal",
        .description      = "Removes room reverberation from speech audio",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "dereverb",
        .category          = "echo",
    },
    {
        .id               = "dereverb-denoiser",
        .effect_selector  = NVAFX_EFFECT_DEREVERB_DENOISER,
        .display_name     = "Noise + Room Echo Removal",
        .description      = "Combined single-pass noise and reverberation removal",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = true,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "dereverb_denoiser",
        .category          = "noise",
    },
    {
        .id               = "aec",
        .effect_selector  = NVAFX_EFFECT_AEC,
        .display_name     = "Acoustic Echo Cancellation",
        .description      = "Removes speaker playback from microphone capture",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 2,  // near-end (mic) + far-end (speaker)
        .output_channels   = 1,
        .model_subdir      = "aec",
        .category          = "echo",
    },
    {
        .id               = "superres",
        .effect_selector  = NVAFX_EFFECT_SUPERRES,
        .display_name     = "Audio Super Resolution",
        .description      = "Upscales low quality audio (8k/16k to 16k/48k)",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = true,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "superres",
        .category          = "enhancement",
    },
    {
        .id               = "studio-voice-hq",
        .effect_selector  = NVAFX_EFFECT_STUDIO_VOICE_HQ,
        .display_name     = "Studio Voice (High Quality)",
        .description      = "Professional microphone enhancement with higher latency",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "studio_voice",
        .category          = "enhancement",
    },
    {
        .id               = "studio-voice-ll",
        .effect_selector  = NVAFX_EFFECT_STUDIO_VOICE_LL,
        .display_name     = "Studio Voice (Low Latency)",
        .description      = "Professional microphone enhancement with lower latency",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "studio_voice",
        .category          = "enhancement",
    },
    {
        .id               = "speaker-focus",
        .effect_selector  = NVAFX_EFFECT_SPEAKER_FOCUS,
        .display_name     = "Speaker Focus",
        .description      = "Isolates the primary speaker from other voices",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "speaker_focus",
        .category          = "voice",
    },
    {
        .id               = "voice-font-hq",
        .effect_selector  = NVAFX_EFFECT_VOICE_FONT_HIGH_QUALITY,
        .display_name     = "Voice Font (High Quality)",
        .description      = "Voice conversion using a reference audio sample",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = true,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "voice_font",
        .category          = "voice",
    },
    {
        .id               = "voice-font-ll",
        .effect_selector  = NVAFX_EFFECT_VOICE_FONT_LOW_LATENCY,
        .display_name     = "Voice Font (Low Latency)",
        .description      = "Voice conversion with lower latency, using a reference audio sample",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = false,
        .has_vad           = false,
        .is_chained        = false,
        .needs_reference_audio = true,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "voice_font",
        .category          = "voice",
    },

    // --- Chained effects ---
    {
        .id               = "denoiser-16k-superres-16k-to-48k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_DENOISER_16k_SUPERRES_16k_TO_48k,
        .display_name     = "Denoise 16k + Super Resolution to 48k",
        .description      = "Denoises at 16kHz then upscales to 48kHz",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "denoiser",
        .category          = "noise",
    },
    {
        .id               = "dereverb-16k-superres-16k-to-48k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_DEREVERB_16k_SUPERRES_16k_TO_48k,
        .display_name     = "Dereverb 16k + Super Resolution to 48k",
        .description      = "Removes reverb at 16kHz then upscales to 48kHz",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "dereverb",
        .category          = "echo",
    },
    {
        .id               = "dereverb-denoiser-16k-superres-16k-to-48k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_DEREVERB_DENOISER_16k_SUPERRES_16k_TO_48k,
        .display_name     = "Dereverb + Denoise 16k + Super Resolution to 48k",
        .description      = "Combined dereverb/denoise at 16kHz then upscales to 48kHz",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "dereverb_denoiser",
        .category          = "noise",
    },
    {
        .id               = "superres-8k-to-16k-denoiser-16k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_SUPERRES_8k_TO_16k_DENOISER_16k,
        .display_name     = "Super Resolution 8k to 16k + Denoise",
        .description      = "Upscales from 8kHz to 16kHz then denoises",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = false,
        .supports_8k      = true,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "superres",
        .category          = "enhancement",
    },
    {
        .id               = "superres-8k-to-16k-dereverb-16k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_SUPERRES_8k_TO_16k_DEREVERB_16k,
        .display_name     = "Super Resolution 8k to 16k + Dereverb",
        .description      = "Upscales from 8kHz to 16kHz then removes reverb",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = false,
        .supports_8k      = true,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "superres",
        .category          = "echo",
    },
    {
        .id               = "superres-8k-to-16k-dereverb-denoiser-16k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_SUPERRES_8k_TO_16k_DEREVERB_DENOISER_16k,
        .display_name     = "Super Resolution 8k to 16k + Dereverb + Denoise",
        .description      = "Upscales from 8kHz to 16kHz then combined dereverb/denoise",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = false,
        .supports_8k      = true,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "superres",
        .category          = "noise",
    },
    {
        .id               = "denoiser-16k-speaker-focus-16k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_DENOISER_16k_SPEAKER_FOCUS_16k,
        .display_name     = "Denoise 16k + Speaker Focus 16k",
        .description      = "Denoises then isolates primary speaker at 16kHz",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = false,
        .supports_16k     = true,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "denoiser",
        .category          = "voice",
    },
    {
        .id               = "denoiser-48k-speaker-focus-48k",
        .effect_selector  = NVAFX_CHAINED_EFFECT_DENOISER_48k_SPEAKER_FOCUS_48k,
        .display_name     = "Denoise 48k + Speaker Focus 48k",
        .description      = "Denoises then isolates primary speaker at 48kHz",
        .type             = MAXINE_EFFECT_AFX,
        .supports_48k     = true,
        .supports_16k     = false,
        .supports_8k      = false,
        .has_intensity     = true,
        .has_vad           = false,
        .is_chained        = true,
        .needs_reference_audio = false,
        .input_channels    = 1,
        .output_channels   = 1,
        .model_subdir      = "denoiser",
        .category          = "voice",
    },
};

#define EFFECT_COUNT (sizeof(effect_table) / sizeof(effect_table[0]))

const struct maxine_effect_info *maxine_effect_find(const char *id)
{
    if (!id)
        return NULL;
    for (unsigned i = 0; i < EFFECT_COUNT; i++) {
        if (strcmp(effect_table[i].id, id) == 0)
            return &effect_table[i];
    }
    return NULL;
}

int maxine_effect_list_all(const struct maxine_effect_info **out_list)
{
    if (out_list)
        *out_list = effect_table;
    return (int)EFFECT_COUNT;
}

const struct maxine_effect_info *maxine_effect_find_by_selector(const char *selector)
{
    if (!selector)
        return NULL;
    for (unsigned i = 0; i < EFFECT_COUNT; i++) {
        if (strcmp(effect_table[i].effect_selector, selector) == 0)
            return &effect_table[i];
    }
    return NULL;
}
